#calc_survival.R
#Author: Boyang Zhao
#Performs surival analysis (both overall survival and disease free surival)
#DEPENDENCIES (datasets): 1) dMAF (generated by analyze_basic.R)
#                         2) siglist_all (generated by analyze_scored.R)
#                         3) dClinicalData_unique (generated by getClinicalData.R)
#GENERATES: in 'dsetSurvivalSummary_dir' directory:
#               1) survivalSigGene_*.csv
#               2) survSigGene.*' in survivalSigGene.RData
#           in 'plots_dir' directory:
#               1) [plots pdf/png]

if(exists("config.avail") && config.avail){ #if configuration settings exist, keep these, clear the rest of workspace
  rm(list=ls()[grep("^[^config\\.].*$",ls())])
} else {
  rm(list=ls())
}

dset_dir <- "../datasets/"
dsetAnalyzed_dir <- paste(dset_dir, "analyzed/", sep="")
dsetScored_dir <- paste(dset_dir, "scored/", sep="")
dsetScoredSummary_dir <- gettextf('%ssummary/summary_pval0.062_exprONLY/', dsetScored_dir)
dsetSurvivalSummary_dir <- gettextf('%ssummary/stratatumorTypeTRUE_mut_age_gender/', dsetScored_dir) #output directory
plots_dir <- gettextf('%splotsSurvival/stratatumorTypeTRUE_mut_age_gender/', dsetScored_dir) #output directory
source('util.R')
library(survival)

#settings
saveLog <- TRUE
surv.savePlots <- TRUE #for survivalAnalysis_indv
surv.strata_tumorType <- TRUE #for survivalAnalysis_indv
surv.coxmodel <- "mut_age_gender" #for survivalAnalysis_indv; possible values 'mut', 'mut_age', 'mut_age_gender'
surv.verboseOutput <- TRUE #for survivalAnalysis_indv
tumorTypesExclude <- c("CELLLINE", "ESCA", "PAAD") #tumor types to exclude

#settings overwrite if configuration settings exist
if(exists("config.avail") && config.avail){
  dset_dir <- config.dset_dir
  dsetAnalyzed_dir <- config.dsetAnalyzed_dir
  dsetScored_dir <- config.dsetScored_dir
  dsetScoredSummary_dir <- config.dsetScoredSummary_dir
  dsetSurvivalSummary_dir <- config.dsetSurvivalSummary_dir
  plots_dir <- config.plotsSurvival_dir
  
  saveLog <-  config.surv.saveLog
  surv.savePlots <- config.surv.savePlots
  surv.strata_tumorType <- config.surv.strata_tumorType
  surv.coxmodel <- config.surv.coxmodel
  surv.verboseOutput <- config.surv.verboseOutput
  tumorTypesExclude <- config.surv.tumorTypesExclude  
}

#quality controls
checkDirExists(dsetAnalyzed_dir)
checkDirExists(dsetScored_dir)
checkDirExists(dsetScoredSummary_dir)
createDir(dsetSurvivalSummary_dir)
if(surv.savePlots){
  createDir(plots_dir)
}

#load datasets
load(paste(dsetAnalyzed_dir,"datasets_analyzed.RData",sep="")) #for mutation dataset ('dMAF')
load(paste(dsetScoredSummary_dir,"sigListGene.RData",sep="")) #for list of significant genes ('siglist_all')
load(paste(dset_dir, "TCGA-clinicaldata/datasets_clinicalData.RData", sep="")) #for clinical data ('dClinicalData_unique')
siglist_all <- siglist_all[!(siglist_all$tumorType %in% tumorTypesExclude),]
dMAF <- dMAF[!(dMAF$tumorType %in% tumorTypesExclude),]

#annotate dMAF with features used for survival stratification
dStrata <- dMAF #dMAFentryMutSame
strata_bool <- paste(dMAF$tumorType, dMAF$geneSymbol, dMAF$aaPos, dMAF$varAA,sep="_") %in% 
  paste(dStrata$tumorType, dStrata$geneSymbol, dStrata$aaPos, dStrata$varAA,sep="_")

dMAF <- cbind(dMAF, strata=strata_bool, stringsAsFactors=FALSE)

#derived parameters
logFilename <- paste(dsetSurvivalSummary_dir,"analyze_scoredSurvival.log",sep="")
surv.dataset.ref <- dMAF #reference dataset used for analysis
surv.dataset.tumorTypes <- dMAF #reference dataset used for search/determine which tumor type to analyze (for pan-cancer)

#start diversion if applicable
if(saveLog){
  sink(logFilename, split=TRUE, append=FALSE)
}

###################################################
# Survival methods
###################################################
survivalAnalysis_indv <- function(geneSymbol,
                                  tumorTypes, 
                                  survmetric = "os", 
                                  dataset.tumorTypes = surv.dataset.tumorTypes,
                                  dataset.ref = surv.dataset.ref,
                                  coxmodel = surv.coxmodel,
                                  strata_tumorType = surv.strata_tumorType,
                                  verboseOutput = surv.verboseOutput,
                                  savePlots = surv.savePlots){
  #Generates Kaplan-Meier and Cox hazard model analysis given gene and tumor type
  #REQUIRES: 1) dClinicalData_unique: clinical data - a dataset loaded from .RData
  #INPUT: 1) gene symbol
  #       2) tumorTypes: a vector of tumor types
  #           if tumorTypes is a vector, survival analysis is a pan-cancer analysis
  #           if value of tumorTypes is 'pan-cancer', then will determine the list of tumor types for which the gene is mutated
  #       3) survmetric can take the value of either "os" (overall survival) or "dfs" (disease-free survival)
  #       4) dataset.tumorTypes: dataset used to search/determine tumor types for pan-cancer analysis;
  #                              only applicable if tumorTypes='pan-cancer'
  #       5) dataset.ref: reference dataset used for survival analysis
  #       6) coxmodel: cox hazard model to use, possible values: 'mut', 'mut_age', 'mut_age_gender'
  #       7) strata_tumorType: for pan-cancer, perform stratified cox hazard model (by tumor type)
  #       8) verboseOutput: boolean for verbose output
  #       9) savePlots: boolean for saving plots
  #OUTPUT: data.frame of median survivals and p-val (log-rank)
  
  #plotsTumor_dir <- paste(plots_dir, paste(vapply(tumorTypes,tumor2filename,"text"),collapse="."), sep="")
  plotsTumor_dir <- paste(plots_dir, ifelse(length(tumorTypes)>1,'pan-cancer',tumor2filename(tumorTypes)), sep="")
  tumorTypes_txt <- paste(tumorTypes,collapse=";")
  
  #quality controls
  #create plots folder if they don't exist
  if(savePlots){
    createDir(plotsTumor_dir)
  }
  if(survmetric != "os" && survmetric != "dfs"){
    message("survmetric in survivalAnalysis_indv can only take values 'os' or 'dfs', defaulting to 'os'...")
    survmetric = "os"
  }
  
  catn("*********************************************")
  catn(gettextf("Survival analysis for %s in %s", geneSymbol, tumorTypes_txt))
  clinicalData <- dClinicalData_unique[!is.na(dClinicalData_unique$os_months) & !is.na(dClinicalData_unique$os_status),]
  
  #get list of tumor types for analysis
  mutTumorTypes <- tumorTypes
  mutTumorTypes_txt <- tumorTypes_txt
  if(length(tumorTypes) < 2 && tumorTypes == "pan-cancer"){
    mutTumorTypes <- unique(dataset.tumorTypes[dataset.tumorTypes$geneSymbol == geneSymbol, 'tumorType'])
    mutTumorTypes <- mutTumorTypes[mutTumorTypes!='CELLLINE'] #exclude cell lines
    mutTumorTypes_txt <- paste(mutTumorTypes,collapse=";")
    catn(gettextf("Detected the following tumor types where %s is mutated: %s", 
                  geneSymbol, mutTumorTypes_txt))
  }
  
  #get all casesIDs
  caseIDs_all <- clinicalData$caseID
  caseIDs_gene <- unique(dataset.ref[dataset.ref$geneSymbol == geneSymbol & dataset.ref$strata, 'caseID']) #for slice of dataset for mutation/feature
  caseIDs_tumor <- unique(dataset.ref[dataset.ref$tumorType %in% mutTumorTypes, 'caseID']) #for slice of dataset for analysis
  
  mutated_bool <- caseIDs_all %in% caseIDs_gene
  tumor_bool <- caseIDs_all %in% caseIDs_tumor
  censor_val <- rep(1,length(caseIDs_all)) #initialize censor value with 1 (not censored)
  switch(survmetric,
         os={
           #overall survival
           censor_val[toupper(clinicalData$os_status) == "LIVING"] <- 0 #censored = 0
           censor_val[is.na(clinicalData$os_status)] <- 0 #will also treat NA as censored data
         },
         dfs={
           #disease free survival
           censor_val[toupper(clinicalData$dfs_status) == "DISEASEFREE"] <- 0 #censored = 0
           censor_val[is.na(clinicalData$dfs_status)] <- 0 #will also treat NA as censored data
         }
  )
  
  survdata <- cbind(clinicalData[tumor_bool,], censor=censor_val[tumor_bool], mutated=mutated_bool[tumor_bool]) 
  
  #preallocate results output data.frame
  survResults <- data.frame(geneSymbol = geneSymbol,
                            tumorType = mutTumorTypes_txt,
                            totalCases = nrow(survdata),
                            mutatedCases = sum(survdata$mutated),
                            t(rep(NA,10)), stringsAsFactors=FALSE)
                            
  #survival analysis
  surv.errMsg <- ""
  if(sum(survdata$mutated) > 2 && sum(!survdata$mutated) > 2){
    if(length(levels(factor(survdata$mutated))) < 2){
      surv.errMsg <- "All entries are either mutated or not mutated - cannot stratify dataset..."
      message(surv.errMsg)
    } else {
      #get survival information of given caseID
      #Kaplan-Meier estimate
      survdata.obj <- Surv(survdata$os_months, survdata$censor)
      surv.KM <- survfit(survdata.obj ~ survdata$mutated, conf.type="none")
      surv.logrank <- survdiff(survdata.obj ~ survdata$mutated)
      
      #Cox proportional hazard models
      surv.PH.defined <- FALSE
      tryCatch({
        if(sum(survdata[survdata$mutated==TRUE,'censor']) < 1 || 
             sum(survdata[survdata$mutated==FALSE,'censor']) < 1){
          warning("Skipping hazard model analysis because one or more of stratified data consists of only censored data...")
        } else{
          if(sum(is.na(survdata$age)>0) | sum(is.na(survdata$gender)>0)){
            #just a note, will continue analysis with na.action=na.omit
            surv.errMsg <- "There are NAs for covariates 'age' or 'gender' field..."
          }
          
          if(length(mutTumorTypes) > 1){ #pan-cancer models
            if(strata_tumorType){
              switch(coxmodel,
                     mut={
                       surv.PH <- coxph(survdata.obj ~ survdata$mutated + strata(survdata$tumorType), na.action=na.omit)
                     },
                     mut_age={
                       surv.PH <- coxph(survdata.obj ~ survdata$mutated + survdata$age + strata(survdata$tumorType), na.action=na.omit)
                     },
                     mut_age_gender={
                       surv.PH <- coxph(survdata.obj ~ survdata$mutated + survdata$age + survdata$gender + strata(survdata$tumorType), na.action=na.omit)
                     },
              )
            } else {
              switch(coxmodel,
                     mut={
                       surv.PH <- coxph(survdata.obj ~ survdata$mutated + survdata$tumorType, na.action=na.omit)
                     },
                     mut_age={
                       surv.PH <- coxph(survdata.obj ~ survdata$mutated + survdata$age + survdata$tumorType, na.action=na.omit)
                     },
                     mut_age_gender={
                       surv.PH <- coxph(survdata.obj ~ survdata$mutated + survdata$age + survdata$gender + survdata$tumorType, na.action=na.omit)
                     },
              )
            }
            
          } else { #individual tumor type models
            switch(coxmodel,
                   mut={
                     surv.PH <- coxph(survdata.obj ~ survdata$mutated, na.action=na.omit)
                   },
                   mut_age={
                     surv.PH <- coxph(survdata.obj ~ survdata$mutated + survdata$age, na.action=na.omit)
                     },
                   mut_age_gender={
                     surv.PH <- coxph(survdata.obj ~ survdata$mutated + survdata$age + survdata$gender, na.action=na.omit)
                     },
            )
          }
          surv.PH.defined <- TRUE
        }
      }, warning = function(w){
        surv.errMsg <<- paste(surv.errMsg, conditionMessage(w), sep=ifelse(surv.errMsg=="","",";"))
        message(surv.errMsg)
        surv.PH.defined <- FALSE
      }, error = function(err){
        surv.errMsg <<- paste(surv.errMsg, conditionMessage(err), sep=ifelse(surv.errMsg=="","",";"))
        message(surv.errMsg)
        surv.PH.defined <- FALSE
      }, finally = {
      })
      
      #print outputs
      if(verboseOutput){
        catn("*** Kaplan-Meier ***")
        print(surv.KM)
        
        catn("*** logrank ***")
        if(sum(is.na(summary(surv.KM)$table[,'median'])) > 0){
          catn("Logrank statistic not available (KM estimate contain NAs)...")
        } else {
          print(surv.logrank)
        }
        
        catn("*** Cox hazard models ***")
        if(!surv.PH.defined){
          catn("Cox hazard model not available...")
        } else{
          print(summary(surv.PH))
          catn("*** Cox hazard models test of proportionality ***")
          print(cox.zph(surv.PH)) #test of proportionality
          #plot(cox.zph(surv.PH))
        }
        cat("\n")
      }
      
      #update output results data.frame
      if(sum(is.na(summary(surv.KM)$table[,'median'])) < 1){
        survResults[,5] <- 1 - pchisq(surv.logrank$chisq, 1)
      }
      
      if(surv.PH.defined){
        surv.PH.summary <- summary(surv.PH)
        survResults[,c(6:ncol(survResults))] <- cbind(t(surv.PH.summary$coefficients[1,]),
                                                      t(surv.PH.summary$conf.int[1,c(3,4)]),
                                                      paste(as.character(surv.PH$formula[c(2,1,3)]), collapse=" "),
                                                      paste(round(cox.zph(surv.PH)$table[,3],4),collapse=";"))
        #proportionality test p-values correspond to p-values for each covariate in specified model, 
        #and last p-value is for GLOBAL
      }
      
      #Plots
      plotfn <- paste(geneSymbol, survmetric, sep=".")
      openPDFdev(plotsTumor_dir, plotfn, savePlots)
      xlabelTxt <- ifelse(survmetric=="os", "Overall survival time (months)", 
                                            "Disease-free survival time (months)")
      plot(surv.KM, lty=c(1,3), xlab=xlabelTxt, ylab="Survival Probability", 
           col=c("black","red"), cex.main = 1,
           main=gettextf("%s in %s, p-val = %1.5f", 
                         geneSymbol, 
                         mutTumorTypes_txt, 
                         ifelse(surv.PH.defined, surv.PH.summary$coefficients[1,5], NA)) )
      legend.txt <- c( gettextf("Not mutated (n=%s)", sum(!survdata$mutated)), 
                       gettextf("Mutated (n=%s)", sum(survdata$mutated)) )
      legend(round(max(survdata$os_months)*(3/5)), 1, legend.txt,
             lty=c(1,3), cex=0.8, col=c("black","red"), text.col=c("black","red"))
      #y.intersp=1.5, text.width=max(strwidth(legend.txt)*1.1)
      saveFig(plotsTumor_dir, plotfn, savePlots)
      dev.off()
    }
  } else {
    surv.errMsg <- "There aren't enough data for survival analysis..."
    message(surv.errMsg)
  }
  
  survResults <- cbind(survResults, surv.errMsg, stringsAsFactors=FALSE)
  names(survResults)[c(5:ncol(survResults))] <- c("logrank_pval", "coef", "hazardRatio", "stdError", "zScore", "pval",
                                                  "lowerCI95", "upperCI95", "model", "proportionalityTest_pval",
                                                  "errorMsg")
  return(survResults)
}

survivalAnalyses <- function(geneSymbols, tumorTypes, survmetric="os", dataset.tumorTypes = surv.dataset.tumorTypes){
  #survival analysis, given a list of gene symbols and corresponding tumor types
  #INPUTS: 1) geneSymbols: list of gene symbols
  #        2) tumorTypes: list of tumorTypes for each item in geneSymbols
  #        3) survmetric accepts either "os" (overall survival) or "dfs" (disease-free survival)
  #        4) dataset.tumorTypes: dataset used to search/determine tumor types for pan-cancer analysis;
  #                               only applicable if tumorTypes='pan-cancer'; default equal to global dataset.tumorTypes value
  #DEPENDENCIES: calls survivalAnalysis_indv per gene and tumorType pair; survmetric and dataset.tumorTypes values are
  #              passed onto survivalAnalysis_indv
  #DEPENDENCIES RQEUIRES: dClinicalData_unique
  #OUTPUTS: list of survival analysis results for each gene item given in input (is stable and matches index between intput/output)
  #         and a filter list of results for only gene item without any errors
  
  results.all <- c()
  for(idx in 1:length(geneSymbols)){
    gene <- geneSymbols[idx]
    tumor <- tumorTypes[idx]
    results_indv <- survivalAnalysis_indv(gene, tumor, survmetric, dataset.tumorTypes)
    results.all <- rbind(results.all, results_indv)
  }
  
  # filter out entries where suvival analysis was not done / had problems
  #results.indv <- results.all[results.all$errorMsg=="",] #filter based on error/warning message
  results.indv <- results.all[!is.na(results.all$coef),] #filter based on existence of NAs
  results.indv <- cbind(results.indv[,1:9],
                        qval=p.adjust(results.indv$pval, method="BH"),
                        results.indv[,10:ncol(results.indv)], stringsAsFactors=FALSE)
  
  return(list(all=results.all, indv=results.indv))
}

survivalAnalysesSet <- function(survmetric){
  #performs individual tumor and pan-cancer survival analyses
  #REQUIRES: siglist_all
  #DEPENDENCIES: calls survivalAnalyses
  #DEPENDENCIES RQEUIRES: dClinicalData_unique
  #INPUTS: survival metric ('os' or 'dfs')
  #OUTPUTs: list of 4 lists (individual tumor type analysis with and without filters; pan-cancer analysis with and without filters)
  
  #Individual tumor type analysis
  catn("++++++++++++++++++++++++++++++++++++++++++++++++++++")
  catn(gettextf("+ Individual Tumor Type Analysis with survival metric = %s", survmetric))
  catn("++++++++++++++++++++++++++++++++++++++++++++++++++++")
  
  siglist <- siglist_all[as.logical(siglist_all$MutSigPass) | as.logical(siglist_all$probPass),]
  r <- survivalAnalyses(siglist$geneSymbol, siglist$tumorType, survmetric)
  survSigGene.indv.all <- r$all
  survSigGene.indv.filtered <- r$indv
 
  
  #Pan-cancer analysis on significant genes at least mutated in 2 tumor types
  #pan-cancer is only done on tumor types where survival analysis was valid from the individual tumor analysis
  catn("++++++++++++++++++++++++++++++++++++++++++++++++++++")
  catn(gettextf("+ Pan-Cancer Analysis with survival metric = %s", survmetric))
  catn("++++++++++++++++++++++++++++++++++++++++++++++++++++")
  
  #count occurrences (# of tumor types) for each gene
  geneCounts <- aggregate(survSigGene.indv.filtered$geneSymbol, 
                          by=list(survSigGene.indv.filtered$geneSymbol), 
                          FUN=length)
  names(geneCounts) <- c("geneSymbol", "count")
  
  geneSymbols <- as.character(geneCounts[geneCounts$count>1, "geneSymbol"])
  tumorTypes <- rep("pan-cancer",length(geneSymbols))
  r <- survivalAnalyses(geneSymbols, tumorTypes, survmetric, survSigGene.indv.filtered)
  survSigGene.panCancer.all <- r$all
  survSigGene.panCancer.filtered <- r$indv
  
  return(list(indv.all = survSigGene.indv.all,
              indv.filtered = survSigGene.indv.filtered,
              panCancer.all = survSigGene.panCancer.all,
              panCancer.filtered = survSigGene.panCancer.filtered))
}

###################################################
# Survival analysis of all significant genes
###################################################
tryCatch({
  
  #overall survival
  r <- survivalAnalysesSet("os")
  survSigGene.indv.os.all = r$indv.all
  survSigGene.indv.os.filtered = r$indv.filtered
  survSigGene.panCancer.os.all = r$panCancer.all
  survSigGene.panCancer.os.filtered = r$panCancer.filtered
  
  
  #disease free survival
  r <- survivalAnalysesSet("dfs")
  survSigGene.indv.dfs.all = r$indv.all
  survSigGene.indv.dfs.filtered = r$indv.filtered
  survSigGene.panCancer.dfs.all = r$panCancer.all
  survSigGene.panCancer.dfs.filtered = r$panCancer.filtered
  
  #save results
  write.csv(survSigGene.indv.os.all,file=paste(dsetSurvivalSummary_dir, "survivalSigGene_indv_os.csv",sep=""))
  write.csv(survSigGene.panCancer.os.all,file=paste(dsetSurvivalSummary_dir, "survivalSigGene_panCancer_os.csv",sep=""))
  write.csv(survSigGene.indv.dfs.all,file=paste(dsetSurvivalSummary_dir, "survivalSigGene_indv_dfs.csv",sep=""))
  write.csv(survSigGene.panCancer.dfs.all,file=paste(dsetSurvivalSummary_dir, "survivalSigGene_panCancer_dfs.csv",sep=""))
  save(survSigGene.indv.os.all,
       survSigGene.indv.os.filtered,
       survSigGene.panCancer.os.all, 
       survSigGene.panCancer.os.filtered,
       survSigGene.indv.dfs.all,
       survSigGene.indv.dfs.filtered,
       survSigGene.panCancer.dfs.all,
       survSigGene.panCancer.dfs.filtered,
       file=paste(dsetSurvivalSummary_dir,"survivalSigGene.RData",sep=""))
  
}, warning = function(w){
  message(conditionMessage(w))
}, error = function(err){
  message(conditionMessage(err))
}, finally = {
  if(saveLog){
    sink() #close diversion
  }
})
